apiVersion: v1
kind: Service
metadata:
  name: ubuntu-focal-ssh
spec:
  externalIPs:
    - 130.226.137.130
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: ubuntu
