apiVersion: v1
kind: Pod
metadata:
  name: jammy
  labels:
    app: jammy
spec:
  containers:
    #- image: ubuntu
  - image: sciencedata/ubuntu_jammy_sciencedata
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    resources:
      limits:
        nvidia.com/gpu: 1
  runtimeClassName: nvidia   #<--- USE THE NVIDIA CONTAINER RUNTIME
  nodeName: worker1
  nodeSelector:              #<--- RUN ON GPU ${NODE_NAME}
    kubernetes.io/hostname: worker1
  restartPolicy: Always

