apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-focal
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu-focal
    image: sciencedata/ubuntu_focal_sciencedata
    volumeMounts:
      - name: sciencedata
        mountPath: "/mnt"
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 22
      protocol: TCP
    env:
    - name: SSH_PUBLIC_KEY
      value: ""
  restartPolicy: Never