#!/bin/bash

TMPDIR="/tmp"
nowSeconds=`date +"%s"`

echo "###" >&2
echo "pod_name|container_name|image_name|pod_ip|node_ip|owner|age|status|ssh_port|ssh_username|https_port|uri" >&2
echo "###" >&2

owner="$@"
user=`echo $owner | awk -F@ '{print $1}'`
domain=`echo $owner | awk -F@ '{print $2}'`

if [[ -n $owner ]]; then
    labels="user=$user,domain=$domain"
fi

echo $(kubectl get pods ${labels:+-l "$labels"} -o json) |\
    jq -r '.items[] | {name: .metadata.name, '\
'cname: [.spec.containers[].name][0]?, '\
'image: [.spec.containers[].image][0]?, '\
'podIP: .status.podIP?, '\
'hostIP: .status.hostIP?, '\
'user: .metadata.labels.user?, '\
'domain: .metadata.labels.domain?, '\
'starttime: .status.startTime?, '\
'state: .status.phase?, '\
'message: .status|(.conditions? // [])|map(select(has("message")).message)[0]?, '\
'status: (.status.containerStatuses[]?.state[]? // []) | join(", "), '\
'sshuser: .spec.containers[]|[.env[]?]|map(select(.name=="USERNAME").value)[0]?, '\
'rpport: .metadata.labels.reverseProxyPort?}' |\
    jq -r '.name+"|"+.cname+"|"+.image+"|"+.podIP+"|"+.hostIP+"|"+.user+"|"+'\
'.domain+"|"+.starttime+"|"+.status+"|"+.state+"|"+.message+"|"+.sshuser+"|"+.rpport+"|"' |\
    while read line; do
    readarray -d '|' -t array < <(echo "$line")
    # 0: name, 1: cname, 2: image, 3: podIP, 4: hostIP, 5: user, 6: domain, 7: starttime, 8: status, 9: state, 10: message, 11: sshuser, 12: rpport
    user="${array[5]}"
    domain="${array[6]}"
    startTime="${array[7]}"
    status="${array[8]}"
    state="${array[9]}"
    message="${array[10]}"

    if [ -n "$startTime" -a "$startTime" != null -a "$state" == "Running" ]; then
        startSeconds=`date -d "$startTime" +"%s"`
        diffSeconds=$((nowSeconds-startSeconds))
    else
        diffSeconds=0
    fi

    if [[ -n "$message" ]] && [[ -z "$status" ]]; then
		    echo "WARNING: $pod has problems: $message" >&2
	  fi

	  if [ -n "$domain" ]; then
		    owner="$user@$domain"
	  else
		    owner="$user"
	  fi
    podName=`echo "$line" | awk '{split($0,a,"|"); print a[1];}'`
	  nodePort=`kubectl get service "${podName}-ssh" -o json 2>/dev/null | jq -r '.spec.ports[].nodePort'`
	  uri=`cat ${TMPDIR}/uri-${podName} 2>/dev/null`
    printf "%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s\n" "${array[0]}" "${array[1]}" "${array[2]}" "${array[3]}"\
           "${array[4]}" "$owner" "$diffSeconds" "$state:$status" "$nodePort" "${array[11]}" "${array[12]}" "$uri"
done

