#!/bin/bash

# run_pod -o owner -k public_key -r nfs_storage_path -l local_storage_path yaml_file
# Notice that the mount point for the nfs and/or local volume must be specified in the yaml file.
# E.g.
# run_pod -o fror@dtu.dk  -k "`cat ~/.ssh/id_rsa.pub`" -r www /root/sciencedata_kubernetes/pod_manifests/ubuntu_sciencedata.yaml
# run_pod -o fror@dtu.dk -l /usr/local/software -p 8888 /root/sciencedata_kubernetes/pod_manifests/jupyter_sciencedata.yaml

logfile='/var/log/kube.log'
# If you have more than one public IP, you may need to hardcode EXTERNAL_IP
EXTERNAL_IP=`hostname -I | sed "s| |\n|g" |  grep -E -v '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)' | head -1`
# ScienceData internal IP. This presumes you've made an entry for sciencedata in /etc/hosts -if not, just hardcode SCIENCEDATA_IP
SCIENCEDATA_IP=`grep -E '\ssciencedata$' /etc/hosts | sed -E 's|^([0-9\.]+)\s.*|\1|'`
if [ -z "$SCIENCEDATA_IP" ]; then
	SCIENCEDATA_IP=10.0.0.13
fi

# If $PEERS is set and contains an unqualified host entry with no IP, check if the host is in /etc/hosts and fill in if it is.
if [ -n $PEERS ]; then
  PEERS_NAMES=`echo $PEERS | sed -E 's| *, *| |g' | sed -E 's| *: *([0-9.]+)|:\1|g' | sed -E 's|:[^ ]*||g'`
  PEERS_IPS=`echo $PEERS | sed -E 's| *, *| |g' | sed -E 's| *: *([0-9.]+)|:\1|g' | sed -E 's|: |:- |g' | sed -E 's|[^ ]+:||g'`
  mypeers=`echo $PEERS | sed 's|,| |g'`
  for mypeer in $mypeers; do
    echo $mypeer | grep -v '\.' | grep -E ':$' >& /dev/null
    if [ "$?" == "0" ]; then
      name=`echo $mypeer | sed 's|:.*||'`
      myip=`grep -E "\s$name$" /etc/hosts | sed -E 's|([\\.0-9]+)\s*(.*)\s*|\1|g'`
      if [[ "$myip" != "" ]]; then
        PEERS=`echo $PEERS | sed -E "s|$name *: *|$name:$myip|"`
      fi
    fi
  done
fi

# This is the trusted, not for users, internal network
SCIENCEDATA_INTERNAL_NET=10.0.
# This is private user network (of the vlan interface)
SCIENCEDATA_PRIVATE_NET=10.2.
# Fallback public DNS name for sciencedata server/silo of the user in question (currently used only for the Caddy web page).
SCIENCEDATA_PUBLIC_IP=sciencedata.dk

cmd="`echo $(readlink -f \"$0\")`"
DIR="`dirname $cmd`"

SSH_SERVICE_YAML_FILE="$DIR/../service_manifests/ssh_service.yaml"
EXTRA_SERVICE_YAML_FILE="$DIR/../service_manifests/extra_service.yaml"
NFS_VOLUME_YAML_FILE="$DIR/../service_manifests/nfs_volume.yaml"
NFS_CLAIM_YAML_FILE="$DIR/../service_manifests/nfs_claim.yaml"
LOCAl_VOLUME_YAML_FILE="$DIR/../service_manifests/local_volume.yaml"
LOCAL_CLAIM_YAML_FILE="$DIR/../service_manifests/local_claim.yaml"
CADDY_FILE="$DIR/../service_manifests/Caddyfile"
TMPDIR="/tmp"
HTTPS_PORTS_FILE="/usr/local/etc/pod_https_ports.txt"
EXTRA_PORTS_FILE="/usr/local/etc/pod_extra_ports.txt"

yaml_file=""
owner=""
ssh_public_key=""
username=""
allowed_ip=""
pod_type=""
nfs_storage_path=""
nfs_files_path=""
dryrun=

#### Define slow functions to run in background after successful pod creation
start_reverse_proxy() {
	# Wait for two minutes for pod to start
	for i in {1..12}; do
		# Find local IP
		pod_ip=$(kubectl get pod "$pod_name" -o json | jq -r '.status.podIP' | sed 's|null||')
		if [[ -n "$pod_ip" ]]; then
			rm ${TMPDIR}/uri-${pod_name} 2>&1 >> "$logfile"
			echo "INFO: Running reverse proxy caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port}" >> "$logfile"
			caddyfile="$TMPDIR/Caddyfile-${pod_ip}-${reverse_proxy_port}-${pod_name}"
			sed "s|WEBPORT|$reverse_proxy_port|" "$CADDY_FILE" > "$caddyfile"
			sed -i "s|PODIP|$pod_ip|" "$caddyfile"
			sed -i "s|PODPORT|$pod_http_port|" "$caddyfile"
			export PATH=/bin/:/usr/bin:/usr/local/bin
			caddy run --adapter caddyfile --config "$caddyfile" &>> "${caddyfile}.log" &
			kubectl exec --stdin ${pod_name} -- cat /tmp/URI 2>>"$logfile" > ${TMPDIR}/uri-${pod_name}
			break
		fi
		sleep 10
	done
	if [[ -z "$pod_ip" ]]; then
		echo "ERROR: pod $pod_name did not start. NOT running reverse proxy caddy reverse-proxy --from https://kube.sciencedata.dk:$reverse_proxy_port --to ${pod_ip}:${pod_http_port}." >> "$logfile"
		exit 1
	else
		# Now wait in the background for another 5 minutes for any /tmp/URI to pop up in the container
		( for i in {1..60}; do
			# If there's a file /tmp/URI, copy it out to /var/run/sciencedata/uri-${pod_name}
				sleep 5
				kubectl exec --stdin ${pod_name} -- cat /tmp/URI 2>>"$logfile" > ${TMPDIR}/uri-${pod_name}
				[[ -e ${TMPDIR}/uri-${pod_name} ]] && [[ ! -s ${TMPDIR}/uri-${pod_name} ]] && rm ${TMPDIR}/uri-${pod_name}
				[[ -s ${TMPDIR}/uri-${pod_name} ]] && break
			done ) 2>&1 >> "$logfile"
	fi
}

while getopts "o:s:k:i:t:r:f:l:m:p:x:d" flag; do
	case "$flag" in
		o)
			# ScienceData userid who will own the pod
			owner=$OPTARG
			;;
		s)
			# Optional ScienceData home server of the userid who will own the pod
			# Only necessary for local-only users
			home_server=$OPTARG
			;;
		k)
			# Public key to be inserted into /root/.ssh/authorized_keys
			ssh_public_key=$OPTARG
			;;
		i)
			# CIDR allowed to access SSH service
			allowed_ip=$OPTARG
			;;
		t)
			# Type of pod. Currently one of: medium, large, gpu1, gpu2
			pod_type=$OPTARG
			;;
		r)
			# Path on home server to be claimed, relative to /tank/storage/owner/
			# Only one of nfs_storage_path and nfs_files_path should be specified.
			# Notice that the mountpoint is specified in the pod yaml
			nfs_storage_path=$OPTARG
			;;
		f)
			# Path on home server to be claimed, relative to /tank/data/owncloud/owner/files/
			# Only one of nfs_storage_path and nfs_files_path should be specified.
			# Notice that the mountpoint is specified in the pod yaml
			nfs_files_path=$OPTARG
			;;
		l)
			# Path on local server to be claimed - absolute.
			# Notice that the mountPath is specified in the pod yaml under name "local"
			# Can be a comma-separated list of paths, but then local_storage_mountpath
			# must be given as well.
			local_storage_path=$OPTARG
			;;
		m)
			# Mountpoint(s) inside the pod/container for local_storage_path.
			# If local_storage_path is just a single path, the mountPath
			# can be specified in the yaml under volumeMounts with name "local"
			local_storage_mountpath=$OPTARG
			;;
		p)
			# Port of web server running in the pod, i.e.
			# the port that will be proxied to
			pod_http_port=$OPTARG
			;;
		x)
			# Extra mapped port of service running in the pod, i.e.
			# the port that will be proxied to (both TCP and UDP).
			# The assigned external port can be inspected after boot.
			# A space-separated list of port numbers is allowed
			pod_extra_port=$OPTARG
			;;
		d)
			# If set, no actions are performed, only reported
			dryrun="yes"
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
	esac
done

yaml_file=${@:$OPTIND:1}
#EXTRA_ARG=${@:$OPTIND+1:1}

if [ -z "$yaml_file" ]; then
	echo "ERROR: Need input file" >&2
	exit 1
fi

if [ ! -f "$yaml_file" ]; then
	echo "ERROR: Input file $yaml_file not found" >&2
	exit 1
fi

if [ ! -s "$yaml_file" ]; then
	echo "ERROR: Input file $yaml_file is empty" >&2
	exit 1
fi

if [ -n "$nfs_files_path" -a -n "$nfs_storage_path" ]; then
	echo "ERROR: Only one of -f and -r may be specified"  >&2
	exit -1
fi

if [ -z "$owner" ]; then
	echo "ERROR: Need owner"  >&2
	exit -1
fi

# Check if the user is attempting to use the host network
grep -iE 'hostnetwork' "$yaml_file"
if [ $? -eq 0 ]; then
	echo "ERROR: Only internal network allowed" >&2
	exit -2
fi

# Check if the user is attempting an NFS volume deployment (mount)
grep -iE 'kind: *Deployment' "$yaml_file"
if [ $? -eq 0 ]; then
	echo "ERROR: Manual mounts are not allowed" >&2
	exit -2
fi

# Check if there is a persistentVolumeClaim claim in the pod yaml
grep -E '^ claimName:' "$yaml_file"
if [ "$?" -eq "0" ]; then
	echo "ERROR: Manual claims are not allowed" >&2
	exit -3
fi

username="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"USERNAME\") | .value'`"
if [ -z "$username" ]; then
	username=root
fi

if [ -z "$ssh_public_key" ]; then
	# No ssh public key given on stdin, try getting it from env
	ssh_public_key="$SSH_PUBLIC_KEY"
	if [ -z "$ssh_public_key" ]; then
		# Try getting ssh public key from yaml
		ssh_public_key="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"SSH_PUBLIC_KEY\") | .value'`"
		if [ -z "$ssh_public_key" ]; then
			echo "WARNING: No SSH public key - it will not be possible to log in" >> "$logfile"
		fi
	fi
fi

if [ -z "$local_storage_path" ]; then
	# No local storage path given on stdin, try getting it from env
	local_storage_path="$LOCAL_STORAGE_PATH"
	if [ -z "$local_storage_path" ]; then
		# Try getting local storage path from yaml- this means no comma-separated multivalue
		local_storage_path="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"MOUNT_SRC\") | .value'`"
	fi
fi

if [ -z "$local_storage_mountpath" ]; then
	# No local storage path given on stdin, try getting it from env
	local_storage_mountpath="$LOCAL_STORAGE_MOUNTPATH"
	if [ -z "$local_storage_mountpath" ]; then
		# Try getting local storage mountpath from yaml - this means no comma-separated multivalue
		local_storage_mountpath="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"MOUNT_DEST\") | .value'`"
	fi
fi

if [ -z "$pod_http_port" ]; then
	# No HTTP port given on stdin, try getting it from env
	pod_http_port="$POD_HTTP_PORT"
	if [ -z "$pod_http_port" ]; then
		# Try getting HTTP port from yaml
		pod_http_port="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"POD_HTTP_PORT\") | .value'`"
		# If port 80 is exposed, we assume it's a web server
		if [ -z "$pod_http_port" ]; then
			pod_http_port="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.ports[]? | select(.containerPort == 80 and .protocol == \"TCP\") | .containerPort'`"
		fi
	fi
fi

if [ -z "$pod_extra_port" ]; then
	# No extra port given on stdin, try getting it from env
	pod_extra_port="$POD_EXTRA_PORT"
	if [ -z "$pod_extra_port" ]; then
		# Try getting extra port from yaml
		pod_extra_port="`cat \"$yaml_file\" | yq -r '.spec.containers[]?.env[]? | select(.name == \"POD_EXTRA_PORT\") | .value'`"
	fi
fi

yaml_user=`cat \"$yaml_file\" | yq -r -y ".metadata.labels.user"`
yaml_domain=`cat \"$yaml_file\" | yq -r -y ".metadata.labels.domain"`

user=`echo $owner | awk -F@ '{print $1}'`
domain=`echo $owner | awk -F@ '{print $2}'`
owner_str=`echo $owner | sed 's|[@._]|-|g'`

if [[ "$yaml_user" != "" && "$yaml_user" != "$user" ]]; then
	echo "ERROR: Not allowed, $yaml_user != $user"  >&2
	exit -1
fi

if [[ "$yaml_domain" != "" && "$yaml_domain" != "$domain" ]]; then
	echo "ERROR: Not allowed, $yaml_domain != $domain"  >&2
	exit -1
fi

pod_base_name="`cat \"$yaml_file\" | yq -r .metadata.name | head -1`"
pod_name="${pod_base_name}-${owner_str}"

# Try up to 9 times to append to name if pod with this name is already running (i.service/jupyter-fror-dtu-dk-ssh. allow 10 copies per user)
new_pod_name="${pod_name}"
for i in {1..9}; do
	kubectl get pod "$new_pod_name" >& /dev/null
	if [ $? -eq 0 ]; then
		new_pod_name="${pod_name}-${i}"
	else
		break
	fi
done
if [ -n "$new_pod_name" ] && [ "$new_pod_name" != "$pod_name" ]; then
	pod_name="$new_pod_name"
fi

# Check if $owner has a public home server configured, otherwise set to $SCIENCEDATA_PUBLIC_IP
public_home_server=`curl --insecure "https://${SCIENCEDATA_IP}/apps/files_sharding/ws/get_user_server.php?user_id=${owner}&internal=no" | sed 's|\\/|/|g' | jq -r '.url' | grep -E 'https*://' | sed -E 's|^https*://||' 2>> "$logfile"`
echo "Home server: $public_home_server" >> "$logfile"
if [ -z "$public_home_server" ]; then
	public_home_server=$SCIENCEDATA_PUBLIC_IP
fi

# Check if home_server is set, otherwise check if $owner has a home server configured, finally to $SCIENCEDATA_IP
if [ -z $home_server ]; then
	home_server=`curl --insecure "https://${SCIENCEDATA_IP}/apps/files_sharding/ws/get_user_server.php?user_id=${owner}&internal=yes" | sed 's|\\/|/|g' | jq -r '.url' | grep -E 'https*://' | sed -E 's|^https*://||' 2> /dev/null`
fi

if [[ -n "$nfs_storage_path" || -n "$nfs_files_path" ]]; then
	web_prefix="files"
	prefix="tank/data/owncloud"
	nfs_path=$nfs_files_path
	suffix="files/"
	nfs_access="ro"
	nfs_access_mode="ReadOnlyMany"
	if [[ -n "$nfs_storage_path" ]]; then
		web_prefix="storage"
		prefix="tank/storage"
			nfs_path=$nfs_storage_path
		suffix=""
		nfs_access="rw"
		nfs_access_mode="ReadWriteMany"
	fi
	if [ -z $home_server ]; then
		home_server=$SCIENCEDATA_IP
	fi
	# Check if directory exists
	dir_exists_http_code=`curl --insecure -H "Depth: 0" -X PROPFIND -o /dev/null -w "%{http_code}" \
	-u ${owner}: "https://${home_server}/${web_prefix}/${nfs_storage_path}/" 2> /dev/null`
	# Create if not
	if [ "$dir_exists_http_code" != "207" ] && [ -z "$dryrun" ]; then
		echo "INFO: https://${home_server}/${web_prefix}/${nfs_storage_path}/ does NOT exist" >> "$logfile"
		dir_create_http_code=$(curl --insecure -X MKCOL -o /dev/null -w "%{http_code}" -u ${owner}: \
								"https://${home_server}/${web_prefix}/${nfs_storage_path}/" 2> /dev/null)
		if [[ $dir_create_http_code != 201 ]]; then
			echo "WARNING: Failed to create storage directory" >> "$logfile"
		fi
	fi
	nfs_volume_path=/${prefix}/${owner}/${suffix}${nfs_path}
	nfs_volume_name="nfs-${home_server}-${owner_str}-$(sed 's|[/\. ]|-|g' <<< ${prefix})-$(echo ${nfs_path} | sed 's|[/\. ]|-|g' | awk '{print tolower($0)}')"
	nfs_claim_name=$nfs_volume_name # just use the same name
	if [ $home_server ]; then
		# Check if the volume is already mounted
		kubectl get pv | grep "^${nfs_volume_name} " >& /dev/null
		if [ "$?" -ne "0" ]; then
			create_nfs_volume="yes"
		else
			kubectl get pv -o yaml | yq '.items[] | (.spec.nfs.server+":"+.spec.nfs.path)' | grep "${home_server}:${nfs_volume_path}" >& /dev/null
			if [ "$?" -ne "0" ]; then
				create_nfs_volume="yes"
			fi
		fi
		# Check if a claim has already been made on $nfs_storage_path
		kubectl get pvc | grep  "^${nfs_claim_name} " >& /dev/null
		if [ "$?" -ne "0" ]; then
			create_nfs_claim="yes"
		fi
	fi
fi

if [ -n "$local_storage_path" ]; then
	while read lsp; do
		local_storage_name=`echo $lsp | sed 's|[/\. ]|-|g' | awk '{print tolower($0)}'`
		# Check if directory exists - TODO: perhaps drop this - the directory only needs to exist on the workers
		#if [ -d "$lsp" ]; then
			kubectl get pv | grep "local-${local_storage_name}" >& /dev/null
			if [ "$?" -ne "0" ]; then
				echo "Will create volume $lsp" >> "$logfile"
				if [ -z "$create_local_volume" ]; then
					create_local_volume="$lsp"
				else
					create_local_volume="$create_local_volume,$lsp"
				fi
			fi
		#fi
		# Check if a claim has already been made on $lsp
		kubectl get pvc | grep  "local-claim-${local_storage_name}" >& /dev/null
		if [ "$?" -ne "0" ]; then
			if [ -z "$create_local_claim" ]; then
				create_local_claim="$lsp"
			else
				create_local_claim="$create_local_claim,$lsp"
			fi
		fi
	done <<< $(echo "$local_storage_path" | sed "s|,|\n|g")
fi

# Find free port for Caddy proxy in range 2000-3000 iff there is a port to forward to
if [[ -n $pod_http_port ]]; then
	# Look for a match in $HTTPS_PORTS_FILE. If found, assign nodePort to this - unless
	# there's already a pod running with this port assigned.
	echo "Looking for $pod_name: in $HTTPS_PORTS_FILE " >> "$logfile"
	if [ -n "`grep ^$pod_name: $HTTPS_PORTS_FILE 2>/dev/null`" ]; then
		if [ -n "`grep ^$pod_name: $HTTPS_PORTS_FILE 2>/dev/null`" ]; then
			reserved_https_port=`grep ^$pod_name: $HTTPS_PORTS_FILE | awk -F: '{print $NF}'`
		fi
		if [ -n "`grep ^$pod_base_name: $HTTPS_PORTS_FILE 2>/dev/null`" ]; then
			reserved_https_port=`grep ^$pod_base_name: $HTTPS_PORTS_FILE | awk -F: '{print $NF}'`
		fi
		# Check if somebody's using it
		if [ -z "`kubectl get -o wide services | grep NodePort | grep :$reserved_https_port/ 2>/dev/null`" ]; then
			if [ "$reserved_https_port" != 443 -a "$reserved_https_port" != 22 ]; then
				reverse_proxy_port=$reserved_https_port
			fi
		else
			echo "Requested port, $reserved_https_port, in use" >> "$logfile"
		fi
	else
		for reverse_proxy_port in {2000..3000}; do
			ps aux | grep "caddy run .*\-\-config ${TMPDIR}/Caddyfile-.*-" >& /dev/null || break
			ps auxw | grep caddy | grep -v "/etc/caddy/Caddyfile" | grep -v grep | grep -E "caddy run .*\-\-config ${TMPDIR}/Caddyfile-.*-${reverse_proxy_port}" >&/dev/null || break
		done
	fi
else
  reverse_proxy_port=''
fi

# This is picked up by start.sh inside the container (for ScienceData-enabled containers)
if [ $home_server ]; then
	export my_home_server=`echo $home_server | sed "s|^$SCIENCEDATA_INTERNAL_NET|$SCIENCEDATA_PRIVATE_NET|"`
fi

if [ -z "$pod_name" ]; then
	echo "ERROR: Parsing .metadata.name from YAML failed" >&2
	exit 2
fi

modified_yaml=$( cat $yaml_file )

# Deal with local mounts (/usr/local/software and CVMFS repositories)
if [ -n "$local_storage_mountpath" ]; then
	while read lsp; do
		local_storage_name=`echo $lsp | sed 's|[/\. ]|-|g' | awk '{print tolower($0)}'`
		# pop off the first element
		lsm=`echo $local_storage_mountpath | sed -E 's|^([^,]+),(.*)|\1|'`
		local_storage_mountpath=`echo $local_storage_mountpath | sed -E 's|^([^,]+),||'`
		echo "Adding volume $lsm to $modified_yaml" >> "$logfile"
		modified_yaml=$( ( yq -r -y ".spec.volumes|= .+ [{\"name\": \"local-${local_storage_name}\", \"persistentVolumeClaim\": {\"claimName\": \"local-claim-${local_storage_name}\"}}]" | yq -r -y ".spec.containers[].volumeMounts|= .+ [{\"name\": \"local-${local_storage_name}\", \"mountPath\":\"$lsm\"}]" ) <<< "$modified_yaml" )
	done <<< $(echo "$local_storage_path" | sed "s|,|\n|g")
fi

### Add "enableServiceLinks: false" to prevent pods in the same namespace to see each others environment variables
### See https://github.com/kubernetes/kubernetes/issues/89033
modified_yaml=$( ( yq -r -y ".spec.enableServiceLinks = false" ) <<< "$modified_yaml" )

### Add memory and CPU limits
if [[ -n "$pod_type" ]]; then
	if [[ "$pod_type" == "small" ]]; then
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.requests.memory = \"128Mi\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.requests.cpu = \"125m\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.memory = \"256Mi\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.cpu = \"250m\"" ) <<< "$modified_yaml" )
	fi
	if [[ "$pod_type" == "medium" || "$pod_type" == "gpu1" || "$pod_type" == "gpu4" ]]; then
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.requests.memory = \"256Mi\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.requests.cpu = \"250m\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.memory = \"512Mi\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.cpu = \"500m\"" ) <<< "$modified_yaml" )
	fi
	if [[ "$pod_type" == "large" ]]; then
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.requests.memory = \"1024Mi\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.requests.cpu = \"500m\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.memory = \"8192Mi\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.cpu = \"2000m\"" ) <<< "$modified_yaml" )	
	fi
	if [[ "$pod_type" == "gpu1" ]]; then
		modified_yaml=$( ( yq -r -y ".spec.runtimeClassName = \"nvidia\"" ) <<< "$modified_yaml" )
		#modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.\"nvidia.com/gpu\" = 1" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r "(.spec.containers[]?.env[]? | select(.name == \"CUDA_VISIBLE_DEVICES_NUM\") | .value) |= \"1\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.nodeSelector.gpusPresent = \"yes\"" ) <<< "$modified_yaml" )
	fi
	if [[ "$pod_type" == "gpu4" ]]; then
		modified_yaml=$( ( yq -r -y ".spec.runtimeClassName = \"nvidia\"" ) <<< "$modified_yaml" )
		#modified_yaml=$( ( yq -r -y ".spec.containers[].resources.limits.\"nvidia.com/gpu\" = 4" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r "(.spec.containers[]?.env[]? | select(.name == \"CUDA_VISIBLE_DEVICES_NUM\") | .value) |= \"4\"" ) <<< "$modified_yaml" )
		modified_yaml=$( ( yq -r -y ".spec.nodeSelector.gpusPresent = \"yes\"" ) <<< "$modified_yaml" )
	fi
fi

### Add user public key to authorized_keys
if [ -n "$ssh_public_key" ]; then
cmd="eval home=~$username \&\& ( ls \$home/.ssh || mkdir \$home/.ssh ) \&\& echo \\\\\"$ssh_public_key\\\\\" >> \$home/.ssh/authorized_keys \&\& chown -R \$username \$home/.ssh \&\& chmod -R go-rw \$home/.ssh"
fi

### Add $allowed_ip to hosts.allow
### This does not work with dropbear because dropbear does not use tcp wrappers.
### It also does not work with openssh because the original source IP is changed by kubernetes.
### "ExternalTrafficPolicy: Local" does not seem to work.
### https://stackoverflow.com/questions/52817382/no-response-when-externaltrafficpolicy-is-set-to-local
### Thus, adding this to the yaml is commented out for now (see below).
#if [ -n "$allowed_ip" ]; then
#cmd="$cmd; grep '^ALL' /etc/hosts.deny || echo ALL >> /etc/hosts.deny; grep $allowed_ip /etc/hosts.deny || echo \\\\\"sshd :  $allowed_ip : allow\\\\\" >> /etc/hosts.allow"
#cmd_add=$(
#	cat <<EOF | sed '$!s/$/\\/' | sed 's/|/\\\|/g'
#      lifecycle:
#        postStart:
#          exec:
#            command: [\"/bin/bash\", \"-c\", \"$cmd\"]
#EOF
#)
#fi

### Find free SSH port and block access if requested
### For some reason, our api-server is configured to assign nodePort in the range 3000 - 32767, NOT
### 30000 - 21767. See https://www.baeldung.com/ops/kubernetes-nodeport-range
### Anyway - for this we start at 30000
active_ports=`kubectl  get services --all-namespaces | grep NodePort | sed -E 's|.*:(.*[0-9]+)/TCP.*|\1|' | sort -n`
for ssh_port in {30000..32768}; do
	echo $active_ports | grep -E "(^|\s+)$ssh_port(\s+|$)" >& /dev/null || break
done
if [[ -z "$ssh_port" || $ssh_port == 32768 ]]; then
	echo "ERROR: No free SSH port found"
	exit 2
fi
# Block SSH access for others than the current client IP
if [ -n "$allowed_ip" ]; then
	# Block access from everywhere
	$run sudo iptables -t raw -A PREROUTING -p tcp --dport $ssh_port -j DROP
	# Allow access from $allowed_ip
	$run sudo iptables -t raw -I PREROUTING -p tcp --dport $ssh_port -s $allowed_ip -j ACCEPT
fi

### Modify pod YAML - ssh public key, metadata, volume. Pass the env variable FILE on.
modified_yaml=$( echo "$modified_yaml" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"SSH_PUBLIC_KEY\") | .value) |= \"$ssh_public_key\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"SD_UID\") | .value) |= \"$owner\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"FILE\") | .value) |= \"$FILE\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"PEERS\") | .value) |= \"$PEERS\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"SETUP_SCRIPT\") | .value) |= \"$SETUP_SCRIPT\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"HOME_SERVER\") | .value) |= \"$my_home_server\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"HTTPS_PORT\") | .value) |= \"$reverse_proxy_port\"" | \
yq -r "(.spec.containers[]?.env[]? | select(.name == \"PUBLIC_HOME_SERVER\") | .value) |= \"$public_home_server\"" | \
sed "s|HOME_SERVER/storage/mathpass|${my_home_server}/storage/mathpass|" | \
yq -r -y ".metadata.name=\"$pod_name\"" |\
yq -r -y ".metadata.labels.user=\"$user\"" | \
yq -r -y ".metadata.labels.domain=\"$domain\"" |\
yq -r -y ".metadata.labels.app=\"$pod_name\"" | \
( [ -z "$pod_http_port" ] && cat || yq -r -y ".metadata.labels.reverseProxyPort=\"$reverse_proxy_port\"" ) |\
( [ -z "$nfs_path" ] && cat || yq -r -y ".spec.volumes|= .+ [{\"name\":\"sciencedata\", \"persistentVolumeClaim\": {\"claimName\": \"${nfs_volume_name}\"}}]" ) #| \
#sed "s|^      env:|${cmd_add}\n      env:|"
### SSH service/port
if [ -n "$ssh_public_key" ]; then
	echo "---"
	cat "$SSH_SERVICE_YAML_FILE"| \
	yq -r -y ".spec.ports[].nodePort=$ssh_port" |\
	yq -r -y ".spec.externalIPs=[\"$EXTERNAL_IP\"]" |\
	yq -r -y ".metadata.name=\"${pod_name}-ssh\"" | \
	yq -r -y ".spec.selector={\"app\":\"$pod_name\"}"
fi
### Extra service/port
if [ -n "$pod_extra_port" ]; then
	i=0
	# We assume $pod_extra_port is a space-separated list. Just one is fine.
	# Notice that if e.g. POD_EXTRA_PORT is set to "3483 9000" in the pod YAML,
	# a matching entry in /usr/local/etc/pod_extra_ports.txt also has to have 2 entries, e.g.
	# ubuntu-noble-lyrion-fror-dtu-dk:3483 9000
	for pod_port in $pod_extra_port; do
		# Look for a match in $EXTRA_PORTS_FILE. If found, assign nodePort to this - unless
		# there's already a pod running with this port assigned.
		if [ -n "`grep ^$pod_name: $EXTRA_PORTS_FILE 2>/dev/null`" ]; then
			reserved_extra_port=`grep ^$pod_name: $EXTRA_PORTS_FILE | awk -F: '{print $NF}'`
		fi
		if [ -n "`grep ^$pod_base_name: $EXTRA_PORTS_FILE 2>/dev/null`" ]; then
			reserved_extra_port=`grep ^$pod_base_name: $EXTRA_PORTS_FILE | awk -F: '{print $NF}'`
		fi
		node_port_line="#"
		if [ -n "$reserved_extra_port" ]; then 
			read -r -a reserved_extra_port_arr <<< "$reserved_extra_port"
			reserved_port=${reserved_extra_port_arr[$i]}
			# Check if somebody's using it
			if [ -z "`kubectl get -o wide services | grep NodePort | grep :$reserved_port/ 2>/dev/null`" ]; then
				if [ "$reserved_port" != 443 -a "$reserved_port" != 22 ]; then
					node_port_line="nodePort: $reserved_port"
				fi
			else
				echo "Requested port, $reserved_port, in use" >> "$logfile"
			fi
		fi
		echo "---"
		cat "$EXTRA_SERVICE_YAML_FILE" | \
		sed "s|EXTRA_PORT|${pod_port}|g" | \
		sed "s|nodePort: NODE_PORT|${node_port_line}|g" | \
		yq -r -y ".spec.externalIPs=[\"$EXTERNAL_IP\"]" |\
		yq -r -y ".metadata.name=\"${pod_name}-extra-${pod_port}\"" |\
		yq -r -y ".spec.selector={\"app\":\"$pod_name\"}"
		i=$(($i+1))
	done
fi
### NFS
if [[ -n "$nfs_storage_path" || -n "$nfs_files_path" ]]; then
	### NFS volume
	if [ -n "$create_nfs_volume" ]; then
		echo "---"
		cat "$NFS_VOLUME_YAML_FILE" | \
		sed "s|NFS_VOLUME_NAME|${nfs_volume_name}|g" | \
		sed "s|NFS_VOLUME_PATH|${nfs_volume_path}|g" | \
		sed "s|NFS_ACCESS_MODE|${nfs_access_mode}|g" | \
		sed "s|NFS_ACCESS|${nfs_access}|g" | \
		sed "s|SERVER_IP|$home_server|g"
	fi
	### NFS persistent volume claim
	if [ -n "$create_nfs_claim" ]; then
		echo "---"
		cat "$NFS_CLAIM_YAML_FILE" | \
		sed "s|NFS_ACCESS_MODE|${nfs_access_mode}|g" | \
		sed "s|NFS_VOLUME_NAME|${nfs_volume_name}|g" | \
		sed "s|NFS_CLAIM_NAME|${nfs_claim_name}|g"
	fi
fi
### Local volume
echo "Creating volumes $create_local_volume" >> "$logfile"
if [ -n "$create_local_volume" ]; then
	while read lsp; do
		local_storage_name=`echo $lsp | sed 's|[/\. ]|-|g' | awk '{print tolower($0)}'`
		echo "---"
		cat "$LOCAl_VOLUME_YAML_FILE" | \
		sed "s|LOCAL_VOLUME_NAME|local-${local_storage_name}|g" | \
		sed "s|LOCAL_STORAGE_PATH|${lsp}|g" | \
		sed "s|LOCAL_STORAGE_CLASS_NAME|manual-${local_storage_name}|g"
	done <<< $(echo "$create_local_volume" | sed "s|,|\n|g")
fi
echo "Creating volumeclaims $create_local_claim" >> "$logfile"
### Local persistent volume claim
if [ -n "$create_local_claim" ]; then
	while read lsp; do
		local_storage_name=`echo $lsp | sed 's|[/\. ]|-|g' | awk '{print tolower($0)}'`
		echo "---"
		cat "$LOCAL_CLAIM_YAML_FILE" | \
		sed "s|LOCAL_CLAIM_NAME|local-claim-${local_storage_name}|g" | \
		sed "s|LOCAL_STORAGE_CLASS_NAME|manual-${local_storage_name}|g"
	done <<< $(echo "$create_local_claim" | sed "s|,|\n|g")
fi
)
### End modify pod YAML

echo "YAML now: $modified_yaml" >> "$logfile"

# Now apply the yaml and save the output of the kubectl command
if [[ -z "$dryrun" ]]; then
	kubectl_output=$( kubectl apply -f - < <(echo "$modified_yaml") )
else
	kubectl_output=$( kubectl apply --validate=true --dry-run=client -f - < <(echo "$modified_yaml") )
fi

echo "$kubectl_output" >> "$logfile"
# If it worked, there should be a line in the output like 'pod/jupyter... created'. In that case report success
regex='.*^pod/[^'$'\n'']+created$.*'
if [[ $kubectl_output =~ $regex ]]; then
	echo "SUCCESS: $pod_name"
	# begin background processes if required
	if [[ -n "$pod_http_port" ]]; then
		start_reverse_proxy >& /dev/null &
	fi
	exit 0
else
	echo "FAILURE: kubectl did not create pod"
	exit 1
fi

