apiVersion: v1
kind: PersistentVolume
metadata:
  name: DISK_VOLUME_NAME
  labels:
    type: disk
spec:
  capacity:
    storage: DISK_VOLUME_SIZE
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: DISK_STORAGE_CLASS_NAME
  hostPath:
    path: DISK_STORAGE_PATH
