apiVersion: v1
kind: Service
metadata:
  name: ubuntu-focal-extra # will be configured by run_pod
spec:
  #externalIPs:
  #  - kube.sciencedata.dk
  type: NodePort
  ports:
    # nodePort will be configured by run_pod if there's a reserved port in /usr/local/etc/kube/pod_extra_ports.txt
    # targetPort will be configured by run_pod from POD_EXTRA_PORTS in the YAML
  - port: NODE_PORT
    nodePort: NODE_PORT
    targetPort: EXTRA_PORT
    name: extra-tcp
    protocol: TCP
  - port: NODE_PORT 
    nodePort: NODE_PORT
    targetPort: EXTRA_PORT
    name: extra-udp
    protocol: UDP
  selector:
    app: ubuntu # will be configured by run_pod
