kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: LOCAL_CLAIM_NAME # will be configured by run_pod
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi 
