apiVersion: v1
kind: PersistentVolume
metadata:
  name: LOCAL_VOLUME_NAME # will be configured by run_pod
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: LOCAL_STORAGE_CLASS_NAME # will be configured by run_pod
  hostPath:
    path: LOCAL_STORAGE_PATH # will be configured by run_pod
