apiVersion: v1
kind: PersistentVolume
metadata:
  name: NFS_VOLUME_NAME # will be configured by run_pod
spec:
  capacity:
    storage: 10Gi # ignored
  volumeMode: Filesystem
  accessModes:
    - NFS_ACCESS_MODE # will be configured by run_pod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - nodiratime
    - async
    - NFS_ACCESS # will be configured by run_pod
  nfs:
    path: NFS_VOLUME_PATH # will be configured by run_pod
    server: SERVER_IP # will be configured by run_pod.sh
  claimRef:
    name: NFS_VOLUME_NAME # will be configured by run_pod
    namespace: default
