kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: NFS_CLAIM_NAME # will be configured by run_pod
spec:
  storageClassName: nfs
  #storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # ignored
  volumeName: NFS_VOLUME_NAME
