kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: NFS_CLAIM_NAME # will be configured by run_pod.sh
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # ignored
